#!/bin/bash

# ==============================================================================
# Hesutils library: miscellaneous helper functions
# ==============================================================================


# DNS config generation utilities
# ------------------------------------------------------------------------------

# Prepare (aka. sanitize) a string that will go into a TXT record:
# - local encoding --> ASCII
# - wrap it at the 255-byte mark
# - add backslash before any double-quote
#
# Reads the data on stdin
# Prints one or more line of sanitized text to stdout.

function prepare_TXT_string {
    iconv -t ascii//translit | fold -w 255 | sed 's/"/\\"/g'
}

