#!/bin/bash

# ==============================================================================
# Hesutils library: miscellaneous helper functions
# ==============================================================================


# DNS config generation utilities
# ------------------------------------------------------------------------------

# To prepare a string that will go into a TXT record:
# - sanitize it by adding backslashes before double-quotes
# - split it into 255-byte chunks
#
# dnsmasq does the splitting itself internally.

function sanitize_TXT { sed 's/"/\\\\"/g' ; }
function fold_TXT     { fold -w 255 ; }

