#!/usr/bin/env bash

# ==============================================================================
#
# Functions to write out the Hesiod TXT records in different formats.
#
# ==============================================================================
#
# This file is part of Hesutils <https://gitlab.com/jflf/hesutils>
# Hesutils Copyright (c) 2019-2021 JFLF
#
# Hesutils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hesutils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Hesutils. If not, see <https://www.gnu.org/licenses/>.
#
# ==============================================================================



# Helper functions
# ------------------------------------------------------------------------------

# On top of the normal GECOS sanitization done in lib_passwd_group, unbound
# needs all single quotes removed. The entire TXT record has to be passed in
# single quotes, and you can't escape a single quote within a string in single
# quotes.

function sanitize_unbound { sed -e "s/'/./g" ; }



# Generate the Hesiod records
# ------------------------------------------------------------------------------

# The function to generate the Hesiod records is split in two parts. In the
# order in which they run, they are:
#
# - hes_output          standard output
# - hes_output_offset   output piped through column for alignment, then sed to
#                       add an offset decided in hes_output (column would eat the
#                       offset if we did it before alignment)
#
# This used to be done in a single function with an exec > >( column | sed ) in
# the middle, but Bash doesn't wait for the termination of the subshell, nor is
# it possible to make it wait. So with many Hesiod records the main process
# would terminate way before the end of the output. Not an issue when redirec-
# ting to a file, but ugly when on the console.


function hes_output_offset {

    # Notes:
    # - numerical indices (eg. ${!uid2user[@]}) are sorted automatically
    # - dnsmasq doesn't support CNAMEs and unbound doesn't expand them, so we
    #   need to repeat the TXT records twice: .user + .UID, .group + .GID...


    # let's start with the SOA record

    if (( CREATEZONE )) && [[ "$SOA" ]] ; then
        echo "${COMMENT} SOA"

        case $OUTPUTFMT in
            unbound )
                printf $'local-data:\t\'%s.\t%s\t%s\tSOA\t' ${HESDOMAIN} "$inttl" "$CLASS"
                echo "${SOA[@]}""'"
                ;;

            bind )
                printf $'@\t%s\t%s\tSOA\t%s %s ( ' "$inttl" "$CLASS" "${SOA[@]:0:2}"
                echo "${SOA[@]:2}" ")"
                echo
                echo "${COMMENT} NS"
                printf $'@\t%s\tNS\t%s\n' "$CLASS" "${SOA[0]}"
                ;;
        esac

        echo
    fi


    # user and UID records
    echo "${COMMENT} Users"

    for uid in ${!uid2user[@]} ; do
        user=${uid2user[$uid]}
        while read line ; do

            case $OUTPUTFMT in
                dnsmasq )
                    printf 'txt-record=%s.%s,"%s"\n' ${user}.passwd $HESDOMAIN "$line"
                    printf 'txt-record=%s.%s,"%s"\n' ${uid}.uid $HESDOMAIN "$line"
                    ;;
                unbound )
                    printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${user}.passwd ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                    printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${uid}.uid ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                    ;;
                bind )
                    printf $'%s\t%s\t%s\tTXT\t"%s"\n' ${user}.passwd "$inttl" "$CLASS" "$line"
                    printf $'%s\t%s\t%s\tCNAME\t%s\n' ${uid}.uid "$inttl" "$CLASS" ${user}.passwd
                    ;;
            esac

        done < <(echo ${hesusers[$user]} | $sanitize)
    done

    echo


    # then group and GID records
    echo "${COMMENT} Groups"

    for gid in ${!gid2group[@]} ; do
        group=${gid2group[$gid]}
        while read line ; do

            case $OUTPUTFMT in
                dnsmasq )
                    printf 'txt-record=%s.%s,"%s"\n' ${group}.group $HESDOMAIN "$line"
                    printf 'txt-record=%s.%s,"%s"\n' ${gid}.gid $HESDOMAIN "$line"
                    ;;
                unbound )
                    printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${group}.group ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                    printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${gid}.gid ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                    ;;
                bind )
                    printf $'%s\t%s\t%s\tTXT\t"%s"\n' ${group}.group "$inttl" "$CLASS" "$line"
                    printf $'%s\t%s\t%s\tCNAME\t%s\n' ${gid}.gid "$inttl" "$CLASS" ${group}.group
                    ;;
            esac

        done < <(echo ${hesgroups[$group]} | $sanitize)
    done

    echo


    # then grplist records
    if (( USERGRPLIST )) ; then
        echo "${COMMENT} Group lists"

        for uid in ${!uid2user[@]} ; do
            user=${uid2user[$uid]}
            while read line ; do

                case $OUTPUTFMT in
                    dnsmasq )
                        printf 'txt-record=%s.%s,"%s"\n' ${user}.grplist $HESDOMAIN "$line"
                        ;;
                    unbound )
                        printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${user}.grplist ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                        ;;
                    bind )
                        printf $'%s\t%s\t%s\tTXT\t"%s"\n' ${user}.grplist "$inttl" "$CLASS" "$line"
                        ;;
                esac

            done < <(echo ${grplists[$user]} | $sanitize)
        done

        echo
    fi


    # and finally filsys records
    if (( FILSYS )) ; then
        echo "${COMMENT} Filesystems"

        for uid in ${!uid2user[@]} ; do
            user=${uid2user[$uid]}
            while read line ; do
                # skip empty lines due to trailing carriage returns
                (( ${#line} )) || continue

                case $OUTPUTFMT in
                    dnsmasq )
                        printf 'txt-record=%s.%s,"%s"\n' ${user}.filsys $HESDOMAIN "$line"
                        ;;
                    unbound )
                        printf $'local-data:\t\'%s.%s.\t%s\t%s\tTXT\t"%s"\'\n' ${user}.filsys ${HESDOMAIN} "$inttl" "$CLASS" "$line"
                        ;;
                    bind )
                        printf $'%s\t%s\t%s\tTXT\t"%s"\n' ${user}.filsys "$inttl" "$CLASS" "$line"
                        ;;
                esac

            done < <(echo "${filsys[$user]}" | $sanitize)

        done
    fi

}



function hes_output {

    # Offset to pretty-print the zone data
    offset=''

    # Which way do we sanitize the strings?
    sanitize=cat

    # Do we need to write a per-record inline TTL?
    inttl=''



    (( dateout )) && echo -e "${COMMENT} Generated by hesgen on $(date)\n"


    # Per-server header, zone definitions and blocking

    case $OUTPUTFMT in
        dnsmasq )
            (( BLOCKATHENA )) && echo "local=/ns.athena.mit.edu/"
            (( BLOCKUPSTREAM )) && echo "local=/${HESDOMAIN}/"
            [[ "$TTL" ]] && echo "local-ttl=${TTL}"
            echo
            ;;

        unbound )
            sanitize=sanitize_unbound

            if (( CREATEZONE )) ; then
                echo "server:"
                offset='    '
            fi

            (( BLOCKATHENA )) && echo -e "${offset}local-zone: \"ns.athena.mit.edu.\" always_nxdomain\n"

            if (( CREATEZONE )) ; then
                if (( BLOCKUPSTREAM )) ; then
                    echo -e "${offset}local-zone: \"${HESDOMAIN}.\" static\n"
                else
                    echo -e "${offset}local-zone: \"${HESDOMAIN}.\" transparent\n"
                fi
                offset='        '
            fi

            [[ "$TTL" ]] && inttl="$TTL"
            ;;

        bind )
            if (( CREATEZONE )) ; then
                echo "\$ORIGIN  ${HESDOMAIN}."
                [[ "$TTL" ]] && echo "\$TTL     ${TTL}"
                echo
            else
                [[ "$TTL" ]] && inttl="$TTL"
            fi
            ;;
    esac


    # Then move on to the aligned records
    # Column aligns the fields, and sed indents non-empty lines by the offset

    hes_output_offset | column -tes $'\t' | sed "s/^./${offset}&/g"
}

